# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.27.0
import dataclasses
import datetime
from typing import Optional


@dataclasses.dataclass()
class Faculty:
    id: int
    university: str
    name: str


@dataclasses.dataclass()
class Lector:
    id: int
    aisid: Optional[int]
    name: str
    surname: str


@dataclasses.dataclass()
class Permission:
    userId: int
    permissions: int


@dataclasses.dataclass()
class Practitioner:
    id: int
    aisid: Optional[int]
    name: str
    surname: str


@dataclasses.dataclass()
class Review:
    id: int
    author: int
    text: str
    deleted: bool
    language: str
    subjectId: int
    lectorId: Optional[int]
    practitionerId: int
    subjectRating: int
    lectorRating: Optional[int]
    practitionerRating: int
    practitionerReview: Optional[str]
    lectorReview: Optional[str]
    yearBeginning: int
    timestamp: datetime.datetime


@dataclasses.dataclass()
class Subject:
    id: int
    name: str
    facultyId: int
    aisid: Optional[int]
    stage: int


@dataclasses.dataclass()
class Telegram:
    """this is will not be here in v2.0"""
    telegramId: int
    userId: int
    chatId: int


@dataclasses.dataclass()
class User:
    id: int
    aisId: Optional[int]
    facultyId: Optional[int]
    eduEmail: Optional[str]
    ISICNum: Optional[int]
    registred: datetime.datetime
